**Week of 6/2**  
Goals:  
>1. Watch seminar talk 
>2. Help Lily get pltlin running so I can test cmplin. 
>3. Get some part of IFSFA up and running  
  
Log:  
>*Monday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kept on with q3da. Didn't actually do much, just translated it line for line– all pretty straightforward for now. Looked at the thing with linoth because it was bothering me. Annoying how there's no direct translation of 'where' in IDL to python as far as I know.  
>*Tuesday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Continued with q3da, changed how I found gaussian in cmplin (astropy modeling isn't working out, maybe because I'm not understanding how it works completely? Just ended up doing it by hand and putting it at the end as a helper function); will also look at it again later. Helped Lily a little bit.
____

**Week of 6/15**  
Goals:  
>1. Watch seminar talk 
>2. Get Lily's data for her, wait for her to get pltlin running so I can test cmplin. 
>3. Make Q3DA-dev branch and start working on translating IFSFA  
  
Log:  
>*Monday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Helped Lily a little; she got ifsf_pg1411.pro to run (yay!). Made q3da-dev branch but didn't put anything in it. Fixed an mistake I made with default values in pltcont. Started translating IFSFA. Should ask what type initdat is in Python.  
>*Tuesday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Worked more on translating IFSFA but I'm barely at line 350 ( ˘︹˘ ). Feel sick; I didn't do as much as I wanted.  
>*Wednesday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Kept translating. Also, I'm sick.   
>*Thursday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Watched seminar, kept translating, have only written about 200 lines in Python.  
>*Friday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Transposed arrays in pltcont, fixed ones in ifsfa, kept translating ifsfa. Maybe should find a way to test it or something.
____

**Week of 6/8**
  
Goals:  
>1. Finish finetuning ifsf_pltcont, post to Slack when happy with output
>2. Begin trying to rewrite ifsf_cmplin  
>3. Watch seminar talk  
  
Log:  
>*Monday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fixed the error in location of masked regions (data in ct_indx in dictionary I made was wrong, has length of 5800 for the particular data I'm using; should be less than length of Wave). Fixed the blue line in compspec (QSO). Both issues were just errors with the data, not the code itself.  
>*Tuesday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sometimes increasing linewidth makes the line wider as well. Thought I had a range problem but actually just needed to do solid_capstyle="butt" so linewidth doesn't project over edge. Translated cmplin.  
>*Wednesday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Watched seminar, finished translating cmplin.  
>*Thursday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Had to help Lily some with her own work but didn't do much. Finished watching seminar.  
>*Friday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Working on consec function referenced in ifsf_pltcont.pro; making it a separate function created in the same file.  
>*Saturday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Finished consec.  
>*Sunday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tried to help Lily get pg_1411.pro to run; she didn't have MPFIT downloaded hence fitspec wouldn't run. Might look for a zip file for IDLUTILS for her since she doesn't have a command line. Error now is that IDL doesn't have permission to delete files and I don't know how to fix that.

_______  
**Week of 6/1**  
  
Goals:  
>1. Test ifsf_pltcont.pro some more. 
>2. Watch seminar, come up with three questions for Friday.  
>3. Get working version of code done by end of the week  
  
Log:
>*Monday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Took out All of the placeholder variables I put in last week to run/test code and see how it came out > made up a very basic dictionary  
>*Tuesday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Working on input/output functionality (created test file to work on it in a simpler form), realized I messed up using arrays (\[\*,i\] in IDL vs. \[:,i\] in Python, I think) so fixed that. Won't output anything when I defined it as a function.  
>*Wednesday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Fixed outputting issue; fixed subplotting/multiplotting formatting. Added to dictionary so data is plotted in all three subplots, messed with the difference between numpy arrays and regular arrays re. the arrays from yesterday. Running function off an input file (a dictionary saved locally onto my computer) without any trouble now, saved as .npy.  
>*Thursday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Things that gave me trouble: indexing an array with another array, what size arrays in dictionary should be (ie. cont_fit and wave are of the same length, which I forget all the time). Still using some filler code when finding yran[1] until I can test with better numbers, since it's dependent on the length of i1, i2, i3, (I think). Plots output and save to a file when subplotting, scaling looks better when plotting three different figures (but each figure has to be saved to a separate file?). Watched seminar talk.  
>*Friday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Working with ticks is seriously so annoying found plt.xticks, np.arrange(first, last, steps) (see below). Mostly worked with the formatting (legend, ticks, scales, line thicknesses, colors, etc.) so it matches the output from pg1411. I think it looks pretty cool yay :)  
>*Saturday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Got IFSFA/ifsf_pg1411 running again; just had to do a git pull (6/6/2020). Looked at struct_host which is the structure that goes in as instr in ifsf_pltcont, set a break point at line 792 in ifsfa. Cont_dat, wave, emline_dat, cont_fit all DOUBLE[6105], compspec DOUBLE[6105, 2] (found from breakpoint at line 109 in ifsf_pltcont).

_______  
**Week of 5/25**  
  
Goals:
>1. Look through fitspec (tags specifically)
>2. Test ifsf_pltcont.pro
>2. Fix ifsf_pltcont.pro (table > dictionary)  

Log:  
>*Monday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Didn't work  
>*Tuesday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Finished writing translation straight without any testing at all  
>*Wednesday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Looked at fitspec as a whole, changed ifsf_pltcont so it uses dictionaries instead of tables, got ifsf_pg1411 to finally work, tried to make up some data and such to toss into ifsf_pltcont  
>*Thursday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Picked up with coming up with data again, either that was done wrong or the plotting procedure I wrote was wrong; both are probably true lol. Don't have much time today.  
>*Friday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Looked more into how the input file should look; checked out ifsfa. Completely redoing what I had plotting-wise in Python :( Had to watch my brother while working; didn't get as much done as I wanted.  
>*Saturday*:  
>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Looked at how to export a dictionary, fixed plots so they don't freak out, etc. etc.


_______
5/18 goals:
>1. Sort out I-9 form
>2. Figure out what to do exactly
>3. Plot something in IDL and Python

_______
Summer goals:
>1. Fully understand the software
>2. Become familiarized with technical vocabulary
>3. Learn how to work collaboratively 


## stuff from pltcont:

In [134]:
#where, AND, this is so long??
wave = [1, 2, 3, 4]
xran1 = [0, 3]
i1 = [None]
i1.pop(0)
for i in wave:
    if i > xran1[0] and i < xran1[1]:
        i1.append(i)
for x in i1:
    print(x)

1
2


  

In [ ]:
#have to use these at each subplot
plt.minorticks_on()
plt.xticks(np.arange(0, 5, 1.0))

In [ ]:
#lines used to save data from IDL code to a file
close, /all
openw, 1, 'wave.txt'
PRINTF, 1, wave

In [ ]:
#lines used to make a python array from file for dictionary (cred. Joy Lim)
file = open("compspec.txt", "r")
arr = np.zeros((6068, 2), dtype=float)
count = 0
for i in file.readlines():
  for j in i.split():
      if count < 6068:
        row = count % 6068
        column = count // 6068
        arr[row][column] = j
        count+=1

In [87]:
#Did this for Lily
file = open("off.txt", "r")
arr = np.zeros((6, 2), dtype=float)
count = 0
row = 0
column = 0
for i in file.readlines():
  for j in i.split():
        arr[row][column] = j
        column+=1
        if column == 2:
            row+=1
            column = 0
print(arr)

[[-120.   90.]
 [ -80.   50.]
 [-130.   50.]
 [ -80.  120.]
 [ -95.   70.]
 [ -95.   50.]]


In [32]:
import numpy as np
print (np.arange(0, 3))

[0 1 2]


In [15]:
#indexing with an array:
h = [11, 22, 33, 44, 5, 66, 7, 88, 9]
index = [4, 3, 7, 8]
h = np.array(h)
h[np.array(index)]

array([ 5, 44, 88,  9])

## stuff from cmplin:

In [130]:
#alternative to IDLAstro's gaussian.pro in cmplin?
from astropy.modeling import models
x = np.arange(-5, 5, .01)
flux = models.Gaussian1D(x, 0, 1) #amp, mean, stdev
print(flux)
#plt.plot(x, flux)

Model: Gaussian1D
Inputs: ('x',)
Outputs: ('y',)
Model set size: 1
Parameters:
         amplitude [1000]     mean stddev
    ------------------------- ---- ------
    -5.0 .. 4.989999999999787  0.0    1.0


gaussian function used:  
>a * math.exp(-(x - b)\*\*2/(2 * c\*\*2))  
  
derivative:  
>(-a * (x - b)) / c\*\*2) / (math.exp((c\*\*2 \* (x - b)\*\*2)/(2 \* c\*\*2))

## Stuff from consec:

In [2]:
#shifting an array to the right
a = [1, 2, 3, 4]
a.insert(0, a.pop())
print(a)

[4, 1, 2, 3]


In [25]:
a = [1, 2, 3, 4]
print(a[-1:] + a[:-1])

[4, 1, 2, 3]


#### ACTUALLY just use np.roll()

In [ ]:
#adding "padding" to a when a is a numpy array
temp = np.concatenate(([a[0]], a))
a = np.concatenate((temp, [a[-1]]))

In [37]:
#checking to see if I made cond1 and cond2 right except they're super duper long
file = open("cond2.txt", "r")
file1 = open("cond2python.txt", "r")
ls = list()
ls1 = list()
count = 0
for i in file.readlines():
    for j in i.split():
        ls.append(int(j))
for i in file1.readlines():
    for j in i.split():
        ls1.append(j)
equal = True
for i in range (0, len(ls)):
    if (ls[i] == 0 and ls1[i] == False) or (ls[i] == 1 and ls1[i] == True):
        equal = False
        print("i: " + str(i))
        print("IDL[i]: " + str(ls[i]) + " python[i]: " + str(ls1[i]))
print(equal)
print(str(len(ls)))
print(str(len(ls1)))
#I made them right

True
5802
5802


"<" means the smaller of the two numbers in IDL, not t/f

## Stuff from Q3DA:

In [89]:
import numpy as np
b = [4.2, 9.0, 16.5, 25.7]
np.array(b).astype("int")

array([ 4,  9, 16, 25])

(don't forget to save files as .py etc or it'll save as a txt file I guess??)

In [31]:
n = '4'
print(n.zfill(3))

i = 5
labin = str(i + 1).zfill(4)
print(labin)

004
0006


In [22]:
# :(
import numpy as np
t = np.array([[1, 2, 3], [4, 5, 6]])
l = len(t[0])
print("number of columns: " + str(l))
print("number of rows: " + str(len(t)))
print("number of dimensions: " + str(t.ndim))
print("number of elements: " + str(np.size(t)))

number of columns: 3
number of rows: 2
number of dimensions: 2
number of elements: 6


In [25]:
import numpy as np
c = np.transpose([[1, 2, 3],[4, 5, 6]])
print(str(type(c)))

<class 'numpy.ndarray'>


In [135]:
#in pg1411.py
import numpy as np

linoth = np.full((2,6), " ", dtype = object) #filler value (' ') was only one element long 
            #so was only taking first character ([) to fit. should probably use fill?
#print("orig: " + str(linoth))
linoth[0, 2] = "[OIII]4959"
linoth[0, 3] = '[OI]6364'
linoth[:, 4] = ['[NII]6548','[NII]6583']
linoth[0, 5] = '[SII]6716'
print(str(linoth))

[[' ' ' ' '[OIII]4959' '[OI]6364' '[NII]6548' '[SII]6716']
 [' ' ' ' ' ' ' ' '[NII]6583' ' ']]


In [137]:
#checking if a file exists by seeing if u can open it (throwing and catching error)
try:
   fo = open("d:\\nonexisting.txt","r")
   #process after opening file
   pass
   #
   fo.close()
except IOError:
   print ("File doesn't exist")

File doesn't exist
